import type { Fact } from "./types";

export const PLACEHOLDER_FACTS: Fact[] = [
  // ── Global / Clinical ──────────────────────────────────────────────────────
  {
    id: "f-001",
    key: "clinical.intended_purpose",
    value:
      "Ambient voice transcription and clinical documentation support for NHS clinicians. Does not make clinical decisions.",
    valueType: "string",
    domain: "clinical",
    tier: "global",
    createdBy: "Sarah M.",
    createdAt: "2024-09-01",
    modifiedBy: "Sarah M.",
    modifiedAt: "2025-01-14",
    dependentDocumentCount: 18,
    relatedFactKeys: ["clinical.risk_classification", "clinical.patient_safety_impact"],
    versions: [
      {
        id: "v-001-2",
        value:
          "Ambient voice transcription and clinical documentation support for NHS clinicians. Does not make clinical decisions.",
        changedBy: "Sarah M.",
        changedAt: "2025-01-14",
        reason: "Clarified 'does not make clinical decisions' per MHRA guidance feedback.",
      },
      {
        id: "v-001-1",
        value:
          "Ambient voice transcription tool for NHS clinical documentation.",
        changedBy: "James R.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-002",
    key: "clinical.risk_classification",
    value: "Class IIa SaMD (MHRA)",
    valueType: "string",
    domain: "clinical",
    tier: "global",
    createdBy: "James R.",
    createdAt: "2024-09-01",
    modifiedBy: "James R.",
    modifiedAt: "2024-09-01",
    dependentDocumentCount: 12,
    relatedFactKeys: ["clinical.intended_purpose", "legal.mhra_registration"],
    versions: [
      {
        id: "v-002-1",
        value: "Class IIa SaMD (MHRA)",
        changedBy: "James R.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-003",
    key: "clinical.patient_safety_impact",
    value:
      "Indirect — supports documentation workflow only. No real-time clinical decision support.",
    valueType: "string",
    domain: "clinical",
    tier: "global",
    createdBy: "Sarah M.",
    createdAt: "2024-09-01",
    modifiedBy: "Priya K.",
    modifiedAt: "2025-02-20",
    dependentDocumentCount: 9,
    relatedFactKeys: ["clinical.intended_purpose"],
    versions: [
      {
        id: "v-003-2",
        value:
          "Indirect — supports documentation workflow only. No real-time clinical decision support.",
        changedBy: "Priya K.",
        changedAt: "2025-02-20",
        reason: "Strengthened wording following DCB0129 review.",
      },
      {
        id: "v-003-1",
        value: "Indirect — documentation support only.",
        changedBy: "Sarah M.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },

  // ── Global / Data ──────────────────────────────────────────────────────────
  {
    id: "f-004",
    key: "data.retention_period",
    value: "7 years post last patient contact",
    valueType: "string",
    domain: "data",
    tier: "global",
    createdBy: "James R.",
    createdAt: "2024-09-01",
    modifiedBy: "James R.",
    modifiedAt: "2025-03-10",
    dependentDocumentCount: 14,
    relatedFactKeys: ["data.processing_location", "data.deletion_process"],
    versions: [
      {
        id: "v-004-2",
        value: "7 years post last patient contact",
        changedBy: "James R.",
        changedAt: "2025-03-10",
        reason: "Updated to align with NHS Records Management Code of Practice 2021.",
      },
      {
        id: "v-004-1",
        value: "8 years",
        changedBy: "James R.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-005",
    key: "data.processing_location",
    value: "United Kingdom only (Microsoft Azure UK South, UK West failover)",
    valueType: "string",
    domain: "data",
    tier: "global",
    createdBy: "Sarah M.",
    createdAt: "2024-09-01",
    modifiedBy: "Sarah M.",
    modifiedAt: "2024-11-05",
    dependentDocumentCount: 11,
    relatedFactKeys: ["technical.hosting_provider", "data.retention_period"],
    versions: [
      {
        id: "v-005-2",
        value: "United Kingdom only (Microsoft Azure UK South, UK West failover)",
        changedBy: "Sarah M.",
        changedAt: "2024-11-05",
        reason: "Added failover region detail.",
      },
      {
        id: "v-005-1",
        value: "United Kingdom only (Microsoft Azure UK South)",
        changedBy: "Sarah M.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-006",
    key: "data.encryption_at_rest",
    value: "AES-256",
    valueType: "string",
    domain: "data",
    tier: "global",
    createdBy: "Priya K.",
    createdAt: "2024-09-01",
    modifiedBy: "Priya K.",
    modifiedAt: "2024-09-01",
    dependentDocumentCount: 8,
    relatedFactKeys: ["data.encryption_in_transit"],
    versions: [
      {
        id: "v-006-1",
        value: "AES-256",
        changedBy: "Priya K.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-007",
    key: "data.encryption_in_transit",
    value: "TLS 1.3",
    valueType: "string",
    domain: "data",
    tier: "global",
    createdBy: "Priya K.",
    createdAt: "2024-09-01",
    modifiedBy: "Priya K.",
    modifiedAt: "2024-09-01",
    dependentDocumentCount: 8,
    relatedFactKeys: ["data.encryption_at_rest"],
    versions: [
      {
        id: "v-007-1",
        value: "TLS 1.3",
        changedBy: "Priya K.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },

  // ── Global / Technical ────────────────────────────────────────────────────
  {
    id: "f-008",
    key: "technical.hosting_provider",
    value: "Microsoft Azure UK South",
    valueType: "string",
    domain: "technical",
    tier: "global",
    createdBy: "Priya K.",
    createdAt: "2024-09-01",
    modifiedBy: "Priya K.",
    modifiedAt: "2024-09-01",
    dependentDocumentCount: 7,
    relatedFactKeys: ["data.processing_location"],
    versions: [
      {
        id: "v-008-1",
        value: "Microsoft Azure UK South",
        changedBy: "Priya K.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-009",
    key: "technical.ai_model",
    value: "claude-sonnet-4-20250514 (Anthropic)",
    valueType: "string",
    domain: "technical",
    tier: "global",
    createdBy: "Priya K.",
    createdAt: "2024-09-01",
    modifiedBy: "Priya K.",
    modifiedAt: "2025-06-01",
    dependentDocumentCount: 5,
    relatedFactKeys: [],
    versions: [
      {
        id: "v-009-2",
        value: "claude-sonnet-4-20250514 (Anthropic)",
        changedBy: "Priya K.",
        changedAt: "2025-06-01",
        reason: "Model upgraded to claude-sonnet-4.",
      },
      {
        id: "v-009-1",
        value: "claude-3-5-sonnet-20241022 (Anthropic)",
        changedBy: "Priya K.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-010",
    key: "technical.uptime_sla",
    value: "99.9% monthly uptime",
    valueType: "string",
    domain: "technical",
    tier: "global",
    createdBy: "James R.",
    createdAt: "2024-10-01",
    modifiedBy: "James R.",
    modifiedAt: "2024-10-01",
    dependentDocumentCount: 4,
    relatedFactKeys: [],
    versions: [
      {
        id: "v-010-1",
        value: "99.9% monthly uptime",
        changedBy: "James R.",
        changedAt: "2024-10-01",
        reason: "Initial value",
      },
    ],
  },

  // ── Global / Legal ────────────────────────────────────────────────────────
  {
    id: "f-011",
    key: "legal.mhra_registration",
    value: "UKCA marked, Class IIa, registration REG-2024-00441",
    valueType: "string",
    domain: "legal",
    tier: "global",
    createdBy: "James R.",
    createdAt: "2024-12-01",
    modifiedBy: "James R.",
    modifiedAt: "2024-12-01",
    dependentDocumentCount: 10,
    relatedFactKeys: ["clinical.risk_classification"],
    versions: [
      {
        id: "v-011-1",
        value: "UKCA marked, Class IIa, registration REG-2024-00441",
        changedBy: "James R.",
        changedAt: "2024-12-01",
        reason: "Registration confirmed.",
      },
    ],
  },
  {
    id: "f-012",
    key: "legal.ico_registration",
    value: "ZA123456",
    valueType: "string",
    domain: "legal",
    tier: "global",
    createdBy: "James R.",
    createdAt: "2024-09-01",
    modifiedBy: "James R.",
    modifiedAt: "2024-09-01",
    dependentDocumentCount: 6,
    relatedFactKeys: [],
    versions: [
      {
        id: "v-012-1",
        value: "ZA123456",
        changedBy: "James R.",
        changedAt: "2024-09-01",
        reason: "Initial value",
      },
    ],
  },

  // ── Global / Evidence ─────────────────────────────────────────────────────
  {
    id: "f-013",
    key: "evidence.nhse_pilot",
    value: "NHSE AVT Registry Pilot, Q3 2024, 12 participating trusts",
    valueType: "string",
    domain: "evidence",
    tier: "global",
    createdBy: "Sarah M.",
    createdAt: "2024-10-15",
    modifiedBy: "Sarah M.",
    modifiedAt: "2025-01-08",
    dependentDocumentCount: 9,
    relatedFactKeys: ["evidence.dtac_status"],
    versions: [
      {
        id: "v-013-2",
        value: "NHSE AVT Registry Pilot, Q3 2024, 12 participating trusts",
        changedBy: "Sarah M.",
        changedAt: "2025-01-08",
        reason: "Final trust count confirmed post-pilot.",
      },
      {
        id: "v-013-1",
        value: "NHSE AVT Registry Pilot, Q3 2024, ongoing",
        changedBy: "Sarah M.",
        changedAt: "2024-10-15",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-014",
    key: "evidence.dtac_status",
    value: "DTAC assessment complete — compliant (October 2024)",
    valueType: "string",
    domain: "evidence",
    tier: "global",
    createdBy: "James R.",
    createdAt: "2024-10-28",
    modifiedBy: "James R.",
    modifiedAt: "2024-10-28",
    dependentDocumentCount: 7,
    relatedFactKeys: ["evidence.nhse_pilot"],
    versions: [
      {
        id: "v-014-1",
        value: "DTAC assessment complete — compliant (October 2024)",
        changedBy: "James R.",
        changedAt: "2024-10-28",
        reason: "Assessment result received.",
      },
    ],
  },

  // ── Module / Mental Health ────────────────────────────────────────────────
  {
    id: "f-015",
    key: "mental-health.session_consent_method",
    value: "Verbal consent captured by clinician prior to session recording",
    valueType: "string",
    domain: "clinical",
    tier: "module",
    module: "mental-health",
    createdBy: "Sarah M.",
    createdAt: "2024-09-15",
    modifiedBy: "Sarah M.",
    modifiedAt: "2024-09-15",
    dependentDocumentCount: 5,
    relatedFactKeys: ["clinical.patient_safety_impact"],
    versions: [
      {
        id: "v-015-1",
        value: "Verbal consent captured by clinician prior to session recording",
        changedBy: "Sarah M.",
        changedAt: "2024-09-15",
        reason: "Initial value",
      },
    ],
  },
  {
    id: "f-016",
    key: "mental-health.ehr_integrations",
    value: "EMIS Web, SystmOne",
    valueType: "list",
    domain: "technical",
    tier: "module",
    module: "mental-health",
    createdBy: "Priya K.",
    createdAt: "2024-09-15",
    modifiedBy: "Priya K.",
    modifiedAt: "2025-01-20",
    dependentDocumentCount: 4,
    relatedFactKeys: ["technical.hosting_provider"],
    versions: [
      {
        id: "v-016-2",
        value: "EMIS Web, SystmOne",
        changedBy: "Priya K.",
        changedAt: "2025-01-20",
        reason: "SystmOne integration completed.",
      },
      {
        id: "v-016-1",
        value: "EMIS Web",
        changedBy: "Priya K.",
        changedAt: "2024-09-15",
        reason: "Initial value",
      },
    ],
  },

  // ── Module / Police ───────────────────────────────────────────────────────
  {
    id: "f-017",
    key: "police.custody_workflow",
    value: "Post-interview transcription only — no real-time recording in custody",
    valueType: "string",
    domain: "clinical",
    tier: "module",
    module: "police",
    createdBy: "James R.",
    createdAt: "2024-11-01",
    modifiedBy: "James R.",
    modifiedAt: "2024-11-01",
    dependentDocumentCount: 3,
    relatedFactKeys: [],
    versions: [
      {
        id: "v-017-1",
        value: "Post-interview transcription only — no real-time recording in custody",
        changedBy: "James R.",
        changedAt: "2024-11-01",
        reason: "Initial value",
      },
    ],
  },

  // ── Module / Neurodevelopmental ───────────────────────────────────────────
  {
    id: "f-018",
    key: "neurodevelopmental.assessment_tools",
    value: "ADOS-2, ADI-R, CARS-2",
    valueType: "list",
    domain: "clinical",
    tier: "module",
    module: "neurodevelopmental",
    createdBy: "Sarah M.",
    createdAt: "2024-11-15",
    modifiedBy: "Sarah M.",
    modifiedAt: "2024-11-15",
    dependentDocumentCount: 4,
    relatedFactKeys: [],
    versions: [
      {
        id: "v-018-1",
        value: "ADOS-2, ADI-R, CARS-2",
        changedBy: "Sarah M.",
        changedAt: "2024-11-15",
        reason: "Initial value",
      },
    ],
  },

  // ── Org-Instance ──────────────────────────────────────────────────────────
  {
    id: "f-019",
    key: "data.retention_period",
    value: "8 years post last patient contact",
    valueType: "string",
    domain: "data",
    tier: "org_instance",
    orgId: "org-bhft",
    orgName: "Berkshire Healthcare NHS FT",
    createdBy: "James R.",
    createdAt: "2025-02-01",
    modifiedBy: "James R.",
    modifiedAt: "2025-02-01",
    dependentDocumentCount: 2,
    relatedFactKeys: ["data.retention_period"],
    versions: [
      {
        id: "v-019-1",
        value: "8 years post last patient contact",
        changedBy: "James R.",
        changedAt: "2025-02-01",
        reason: "BHFT local policy requires 8-year retention.",
      },
    ],
  },
  {
    id: "f-020",
    key: "technical.ehr_system",
    value: "RiO (Servelec)",
    valueType: "string",
    domain: "technical",
    tier: "org_instance",
    orgId: "org-oxleas",
    orgName: "Oxleas NHS FT",
    createdBy: "Priya K.",
    createdAt: "2025-01-10",
    modifiedBy: "Priya K.",
    modifiedAt: "2025-01-10",
    dependentDocumentCount: 3,
    relatedFactKeys: [],
    versions: [
      {
        id: "v-020-1",
        value: "RiO (Servelec)",
        changedBy: "Priya K.",
        changedAt: "2025-01-10",
        reason: "Oxleas confirmed RiO as their EHR.",
      },
    ],
  },
];
