import type { AuditEvent } from "./types";

export const PLACEHOLDER_AUDIT_EVENTS: AuditEvent[] = [
  // ── March 2025 ─────────────────────────────────────────────────────────
  {
    id: "ae-001",
    type: "fact.updated",
    category: "knowledge-base",
    actor: "James R.",
    actorRole: "editor",
    timestamp: "2025-03-10T09:14:22Z",
    summary: "Updated data.retention_period — global fact changed from '8 years' to '7 years post last patient contact'",
    relatedEntityType: "fact",
    relatedEntityId: "f-004",
    relatedEntityLabel: "data.retention_period",
    detail: {
      fact_key: "data.retention_period",
      tier: "global",
      old_value: "8 years",
      new_value: "7 years post last patient contact",
      reason: "Updated to align with NHS Records Management Code of Practice 2021.",
      dependent_documents_flagged: 14,
    },
  },
  {
    id: "ae-002",
    type: "document.stale",
    category: "document",
    actor: "System",
    actorRole: "system",
    timestamp: "2025-03-10T09:14:23Z",
    summary: "2 documents marked stale following update to data.retention_period",
    relatedEntityType: "fact",
    relatedEntityId: "f-004",
    relatedEntityLabel: "data.retention_period",
    detail: {
      trigger_fact_key: "data.retention_period",
      documents_affected: 2,
      affected_doc_ids: "doc-004, doc-010",
      affected_orgs: "Oxleas NHS FT, Mersey Care NHS FT",
    },
  },
  {
    id: "ae-003",
    type: "generation.completed",
    category: "generation",
    actor: "Priya K.",
    actorRole: "editor",
    timestamp: "2025-03-05T14:32:01Z",
    summary: "Generated section 'Safety Claims' for BHFT Clinical Safety Case using prompt clinical-safety.crms-intro v2",
    relatedEntityType: "document",
    relatedEntityId: "doc-003",
    relatedEntityLabel: "BHFT Clinical Safety Case",
    detail: {
      document_id: "doc-003",
      document_name: "Clinical Safety Case — Berkshire Healthcare NHS FT",
      section: "Safety Claims",
      prompt_key: "clinical-safety.crms-intro",
      prompt_version: 2,
      model: "claude-sonnet-4-20250514",
      facts_supplied: "clinical.intended_purpose, clinical.patient_safety_impact, mental-health.session_consent_method",
      tokens_input: 1842,
      tokens_output: 412,
      duration_ms: 3210,
      generation_log_id: "gl-0098",
    },
  },
  {
    id: "ae-004",
    type: "document.section_approved",
    category: "document",
    actor: "Priya K.",
    actorRole: "editor",
    timestamp: "2025-03-05T14:55:18Z",
    summary: "Approved section 'System Overview and Intended Use' in BHFT Clinical Safety Case",
    relatedEntityType: "document",
    relatedEntityId: "doc-003",
    relatedEntityLabel: "BHFT Clinical Safety Case",
    detail: {
      document_id: "doc-003",
      section_title: "System Overview and Intended Use",
      approved_by: "Priya K.",
      content_edited: false,
      generation_log_id: "gl-0095",
    },
  },
  {
    id: "ae-005",
    type: "prompt.version_created",
    category: "prompt",
    actor: "Priya K.",
    actorRole: "editor",
    timestamp: "2025-03-01T10:00:00Z",
    summary: "Created new version v3 of ig-questionnaire.data-controller — pending approval",
    relatedEntityType: "prompt",
    relatedEntityId: "p-005",
    relatedEntityLabel: "IG — Data Controller and Processor Details",
    detail: {
      prompt_key: "ig-questionnaire.data-controller",
      new_version: 3,
      previous_version: 2,
      status: "suggested",
      change_notes: "Added sub-processor clarification for Microsoft Azure following IG lead query at BHFT.",
    },
  },

  // ── February 2025 ──────────────────────────────────────────────────────
  {
    id: "ae-006",
    type: "fact.created",
    category: "knowledge-base",
    actor: "James R.",
    actorRole: "editor",
    timestamp: "2025-02-01T11:22:00Z",
    summary: "Created org-instance fact data.retention_period for Berkshire Healthcare NHS FT",
    relatedEntityType: "fact",
    relatedEntityId: "f-019",
    relatedEntityLabel: "data.retention_period (BHFT override)",
    detail: {
      fact_key: "data.retention_period",
      tier: "org_instance",
      org: "Berkshire Healthcare NHS FT",
      org_id: "org-bhft",
      value: "8 years post last patient contact",
      reason: "BHFT local policy requires 8-year retention.",
    },
  },
  {
    id: "ae-007",
    type: "prompt.rejected",
    category: "prompt",
    actor: "James R.",
    actorRole: "admin",
    timestamp: "2025-02-10T16:45:00Z",
    summary: "Rejected prompt ig-questionnaire.third-party-processors — insufficient DPA detail",
    relatedEntityType: "prompt",
    relatedEntityId: "p-012",
    relatedEntityLabel: "IG — Third-Party Data Processors",
    detail: {
      prompt_key: "ig-questionnaire.third-party-processors",
      version_rejected: 1,
      rejected_by: "James R.",
      rejection_reason: "Too vague on DPA details and GDPR Article 28 compliance. Rewrite needed.",
    },
  },
  {
    id: "ae-008",
    type: "document.approved",
    category: "document",
    actor: "James R.",
    actorRole: "editor",
    timestamp: "2025-02-01T13:10:00Z",
    summary: "Document approved: NHS IG Questionnaire for Oxleas NHS FT v1",
    relatedEntityType: "document",
    relatedEntityId: "doc-005",
    relatedEntityLabel: "NHS IG Questionnaire — Oxleas NHS FT",
    detail: {
      document_id: "doc-005",
      document_name: "NHS IG Questionnaire — Oxleas NHS FT",
      version: 1,
      total_sections: 1,
      approved_by: "James R.",
    },
  },
  {
    id: "ae-009",
    type: "org.module_changed",
    category: "organisation",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2025-02-01T09:00:00Z",
    summary: "Neurodevelopmental module activated for Oxleas NHS FT",
    relatedEntityType: "organisation",
    relatedEntityId: "org-oxleas",
    relatedEntityLabel: "Oxleas NHS FT",
    detail: {
      org: "Oxleas NHS FT",
      org_id: "org-oxleas",
      module: "neurodevelopmental",
      change: "activated",
      previous_modules: "mental-health",
      new_modules: "mental-health, neurodevelopmental",
      documents_re_evaluated: 2,
    },
  },

  // ── January 2025 ───────────────────────────────────────────────────────
  {
    id: "ae-010",
    type: "fact.updated",
    category: "knowledge-base",
    actor: "Sarah M.",
    actorRole: "editor",
    timestamp: "2025-01-14T10:30:00Z",
    summary: "Updated clinical.intended_purpose — clarified 'does not make clinical decisions' per MHRA feedback",
    relatedEntityType: "fact",
    relatedEntityId: "f-001",
    relatedEntityLabel: "clinical.intended_purpose",
    detail: {
      fact_key: "clinical.intended_purpose",
      tier: "global",
      old_value: "Ambient voice transcription tool for NHS clinical documentation.",
      new_value: "Ambient voice transcription and clinical documentation support for NHS clinicians. Does not make clinical decisions.",
      reason: "Clarified 'does not make clinical decisions' per MHRA guidance feedback.",
      dependent_documents_flagged: 18,
    },
  },
  {
    id: "ae-011",
    type: "document.approved",
    category: "document",
    actor: "Sarah M.",
    actorRole: "editor",
    timestamp: "2025-01-14T15:30:00Z",
    summary: "Document approved: DCB0129 CRMP for Berkshire Healthcare NHS FT v3",
    relatedEntityType: "document",
    relatedEntityId: "doc-001",
    relatedEntityLabel: "DCB0129 CRMP — Berkshire Healthcare NHS FT",
    detail: {
      document_id: "doc-001",
      document_name: "DCB0129 Clinical Risk Management Plan — Berkshire Healthcare NHS FT",
      version: 3,
      total_sections: 6,
      sections_edited: 0,
      approved_by: "Sarah M.",
    },
  },
  {
    id: "ae-012",
    type: "prompt.approved",
    category: "prompt",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2025-01-20T11:00:00Z",
    summary: "Approved prompt evidence.clinical-pilot-summary v1",
    relatedEntityType: "prompt",
    relatedEntityId: "p-008",
    relatedEntityLabel: "Evidence — Clinical Pilot Summary",
    detail: {
      prompt_key: "evidence.clinical-pilot-summary",
      version: 1,
      approved_by: "Sarah M.",
      output_format: "prose",
      input_fact_keys: "evidence.nhse_pilot, evidence.dtac_status, clinical.risk_classification",
    },
  },
  {
    id: "ae-013",
    type: "fact.updated",
    category: "knowledge-base",
    actor: "Priya K.",
    actorRole: "editor",
    timestamp: "2025-01-20T09:15:00Z",
    summary: "Updated mental-health.ehr_integrations — added SystmOne integration",
    relatedEntityType: "fact",
    relatedEntityId: "f-016",
    relatedEntityLabel: "mental-health.ehr_integrations",
    detail: {
      fact_key: "mental-health.ehr_integrations",
      tier: "module",
      module: "mental-health",
      old_value: "EMIS Web",
      new_value: "EMIS Web, SystmOne",
      reason: "SystmOne integration completed.",
      dependent_documents_flagged: 4,
    },
  },
  {
    id: "ae-014",
    type: "generation.completed",
    category: "generation",
    actor: "James R.",
    actorRole: "editor",
    timestamp: "2025-01-10T14:05:00Z",
    summary: "Generated all 4 sections for Oxleas NHS IG Questionnaire using ig-questionnaire prompts",
    relatedEntityType: "document",
    relatedEntityId: "doc-005",
    relatedEntityLabel: "NHS IG Questionnaire — Oxleas NHS FT",
    detail: {
      document_id: "doc-005",
      document_name: "NHS IG Questionnaire — Oxleas NHS FT",
      sections_generated: 1,
      prompts_used: "ig-questionnaire.data-controller v2",
      model: "claude-sonnet-4-20250514",
      total_tokens_input: 2104,
      total_tokens_output: 890,
      total_duration_ms: 7842,
    },
  },
  {
    id: "ae-015",
    type: "document.submitted",
    category: "document",
    actor: "James R.",
    actorRole: "editor",
    timestamp: "2025-01-10T09:00:00Z",
    summary: "NHS IG Questionnaire for Berkshire Healthcare NHS FT v2 submitted to trust",
    relatedEntityType: "document",
    relatedEntityId: "doc-002",
    relatedEntityLabel: "NHS IG Questionnaire — Berkshire Healthcare NHS FT",
    detail: {
      document_id: "doc-002",
      document_name: "NHS IG Questionnaire — Berkshire Healthcare NHS FT",
      version: 2,
      submitted_by: "James R.",
      submitted_to: "Tom Redman — IG Lead, Berkshire Healthcare NHS FT",
    },
  },

  // ── December 2024 ──────────────────────────────────────────────────────
  {
    id: "ae-016",
    type: "org.created",
    category: "organisation",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2024-12-01T10:00:00Z",
    summary: "Organisation added: Mersey Care NHS FT (ODS: RW4) with Mental Health module",
    relatedEntityType: "organisation",
    relatedEntityId: "org-mersey",
    relatedEntityLabel: "Mersey Care NHS FT",
    detail: {
      org_name: "Mersey Care NHS Foundation Trust",
      ods_code: "RW4",
      region: "North West",
      initial_modules: "mental-health",
      created_by: "Sarah M.",
    },
  },
  {
    id: "ae-017",
    type: "document.submitted",
    category: "document",
    actor: "Sarah M.",
    actorRole: "editor",
    timestamp: "2024-12-20T15:30:00Z",
    summary: "DCB0129 CRMP for Norfolk and Suffolk NHS FT v1 submitted to trust",
    relatedEntityType: "document",
    relatedEntityId: "doc-012",
    relatedEntityLabel: "DCB0129 CRMP — Norfolk and Suffolk NHS FT",
    detail: {
      document_id: "doc-012",
      document_name: "DCB0129 Clinical Risk Management Plan — Norfolk and Suffolk NHS FT",
      version: 1,
      submitted_by: "Sarah M.",
      submitted_to: "Dr. Paul Mistry — Clinical Risk Owner, Norfolk and Suffolk NHS FT",
    },
  },
  {
    id: "ae-018",
    type: "fact.created",
    category: "knowledge-base",
    actor: "James R.",
    actorRole: "editor",
    timestamp: "2024-12-01T09:30:00Z",
    summary: "Created global fact legal.mhra_registration — UKCA Class IIa registration confirmed",
    relatedEntityType: "fact",
    relatedEntityId: "f-011",
    relatedEntityLabel: "legal.mhra_registration",
    detail: {
      fact_key: "legal.mhra_registration",
      tier: "global",
      domain: "legal",
      value: "UKCA marked, Class IIa, registration REG-2024-00441",
      reason: "Registration confirmed.",
    },
  },

  // ── November 2024 ──────────────────────────────────────────────────────
  {
    id: "ae-019",
    type: "prompt.approved",
    category: "prompt",
    actor: "James R.",
    actorRole: "admin",
    timestamp: "2024-11-10T14:00:00Z",
    summary: "Approved 3 IG Questionnaire prompts: data-controller v2, data-retention v1, security-measures v1",
    relatedEntityType: "prompt",
    relatedEntityId: "p-005",
    relatedEntityLabel: "IG — Data Controller and Processor Details",
    detail: {
      prompts_approved: "ig-questionnaire.data-controller v2, ig-questionnaire.data-retention v1, ig-questionnaire.security-measures v1",
      approved_by: "James R.",
    },
  },
  {
    id: "ae-020",
    type: "fact.updated",
    category: "knowledge-base",
    actor: "Sarah M.",
    actorRole: "editor",
    timestamp: "2024-11-05T11:20:00Z",
    summary: "Updated data.processing_location — added UK West failover region",
    relatedEntityType: "fact",
    relatedEntityId: "f-005",
    relatedEntityLabel: "data.processing_location",
    detail: {
      fact_key: "data.processing_location",
      tier: "global",
      old_value: "United Kingdom only (Microsoft Azure UK South)",
      new_value: "United Kingdom only (Microsoft Azure UK South, UK West failover)",
      reason: "Added failover region detail.",
      dependent_documents_flagged: 11,
    },
  },
  {
    id: "ae-021",
    type: "org.created",
    category: "organisation",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2024-11-01T09:00:00Z",
    summary: "Organisation added: Oxleas NHS FT (ODS: RQY) with Mental Health module",
    relatedEntityType: "organisation",
    relatedEntityId: "org-oxleas",
    relatedEntityLabel: "Oxleas NHS FT",
    detail: {
      org_name: "Oxleas NHS Foundation Trust",
      ods_code: "RQY",
      region: "South East",
      initial_modules: "mental-health",
      created_by: "Sarah M.",
    },
  },

  // ── October 2024 ───────────────────────────────────────────────────────
  {
    id: "ae-022",
    type: "prompt.approved",
    category: "prompt",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2024-10-15T10:00:00Z",
    summary: "Approved 4 clinical safety prompts: crms-intro v2, hazard-identification v1, risk-estimation v1, risk-controls v1",
    relatedEntityType: "prompt",
    relatedEntityId: "p-001",
    relatedEntityLabel: "DCB0129 — CRMS Introduction",
    detail: {
      prompts_approved: "clinical-safety.crms-intro v2, clinical-safety.hazard-identification v1, risk-management.risk-estimation v1, risk-management.risk-controls v1",
      approved_by: "Sarah M.",
    },
  },
  {
    id: "ae-023",
    type: "document.created",
    category: "document",
    actor: "Sarah M.",
    actorRole: "editor",
    timestamp: "2024-10-01T11:00:00Z",
    summary: "Created DCB0129 CRMP for Berkshire Healthcare NHS FT — generation initiated",
    relatedEntityType: "document",
    relatedEntityId: "doc-001",
    relatedEntityLabel: "DCB0129 CRMP — Berkshire Healthcare NHS FT",
    detail: {
      document_type: "DCB0129 Clinical Risk Management Plan",
      org: "Berkshire Healthcare NHS FT",
      active_modules: "mental-health",
      created_by: "Sarah M.",
    },
  },

  // ── September 2024 ─────────────────────────────────────────────────────
  {
    id: "ae-024",
    type: "org.created",
    category: "organisation",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2024-09-01T09:00:00Z",
    summary: "Organisation added: Berkshire Healthcare NHS FT (ODS: RWX) — first trust onboarded",
    relatedEntityType: "organisation",
    relatedEntityId: "org-bhft",
    relatedEntityLabel: "Berkshire Healthcare NHS FT",
    detail: {
      org_name: "Berkshire Healthcare NHS Foundation Trust",
      ods_code: "RWX",
      region: "South East",
      initial_modules: "mental-health",
      created_by: "Sarah M.",
    },
  },
  {
    id: "ae-025",
    type: "user.login",
    category: "auth",
    actor: "Sarah M.",
    actorRole: "admin",
    timestamp: "2024-09-01T08:55:00Z",
    summary: "User login: Sarah M. (admin)",
    detail: {
      user: "Sarah M.",
      role: "admin",
      ip_address: "10.0.0.1",
      auth_provider: "Microsoft Entra ID",
    },
  },
];
