import type { Organisation } from "./types";

export const PLACEHOLDER_ORGS: Organisation[] = [
  {
    id: "org-bhft",
    name: "Berkshire Healthcare NHS Foundation Trust",
    shortName: "Berkshire Healthcare NHS FT",
    odsCode: "RWX",
    region: "South East",
    activeModules: ["mental-health"],
    onboardedAt: "2024-09-01",
    lastActivityAt: "2025-03-05",
    contacts: [
      { name: "Dr. Claire Henson", role: "Clinical Risk Owner", email: "c.henson@berkshire.nhs.uk" },
      { name: "Tom Redman", role: "IG Lead", email: "t.redman@berkshire.nhs.uk" },
      { name: "Priya Shah", role: "Procurement Lead", email: "p.shah@berkshire.nhs.uk" },
    ],
  },
  {
    id: "org-oxleas",
    name: "Oxleas NHS Foundation Trust",
    shortName: "Oxleas NHS FT",
    odsCode: "RQY",
    region: "South East",
    activeModules: ["mental-health", "neurodevelopmental"],
    onboardedAt: "2024-11-01",
    lastActivityAt: "2025-03-10",
    notes: "Neurodevelopmental module activated Feb 2025. CAMHS pilot ongoing.",
    contacts: [
      { name: "Dr. Amir Johal", role: "Clinical Risk Owner", email: "a.johal@oxleas.nhs.uk" },
      { name: "Sandra Osei", role: "IG Lead", email: "s.osei@oxleas.nhs.uk" },
    ],
  },
  {
    id: "org-cnwl",
    name: "Central and North West London NHS Foundation Trust",
    shortName: "Central and North West London NHS FT",
    odsCode: "RV3",
    region: "London",
    activeModules: ["mental-health", "police"],
    onboardedAt: "2025-01-15",
    lastActivityAt: "2025-03-20",
    notes: "Police module in pilot with Metropolitan Police custody suites.",
    contacts: [
      { name: "Dr. Fiona Weir", role: "Clinical Risk Owner", email: "f.weir@cnwl.nhs.uk" },
      { name: "Marcus Bell", role: "IG Lead", email: "m.bell@cnwl.nhs.uk" },
    ],
  },
  {
    id: "org-avon",
    name: "Avon and Wiltshire Mental Health Partnership NHS Trust",
    shortName: "Avon and Wiltshire MHP NHS Trust",
    odsCode: "RVN",
    region: "South West",
    activeModules: ["mental-health"],
    onboardedAt: "2024-09-15",
    lastActivityAt: "2025-01-20",
    contacts: [
      { name: "Dr. Ruth Calloway", role: "Clinical Risk Owner", email: "r.calloway@awp.nhs.uk" },
      { name: "James Patel", role: "IG Lead", email: "j.patel@awp.nhs.uk" },
    ],
  },
  {
    id: "org-mersey",
    name: "Mersey Care NHS Foundation Trust",
    shortName: "Mersey Care NHS FT",
    odsCode: "RW4",
    region: "North West",
    activeModules: ["mental-health", "patient-crm"],
    onboardedAt: "2024-12-01",
    lastActivityAt: "2025-03-28",
    notes: "Patient CRM portal module under evaluation.",
    contacts: [
      { name: "Dr. Helen Cross", role: "Clinical Risk Owner", email: "h.cross@merseycare.nhs.uk" },
      { name: "David Nwachukwu", role: "IG Lead", email: "d.nwachukwu@merseycare.nhs.uk" },
    ],
  },
  {
    id: "org-norfolk",
    name: "Norfolk and Suffolk NHS Foundation Trust",
    shortName: "Norfolk and Suffolk NHS FT",
    odsCode: "TAF",
    region: "East of England",
    activeModules: ["mental-health"],
    onboardedAt: "2024-11-01",
    lastActivityAt: "2024-12-20",
    contacts: [
      { name: "Dr. Paul Mistry", role: "Clinical Risk Owner", email: "p.mistry@nsft.nhs.uk" },
      { name: "Anna Kowalczyk", role: "IG Lead", email: "a.kowalczyk@nsft.nhs.uk" },
    ],
  },
];
